{
 "title": "Hadoop Metrics From JMX",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namenode",
    "label": "Namenode",
    "query": "label_values(hadoop_namenode_fs_name_system_block_capacity, host)"
   },
   {
    "name": "Host",
    "label": "Host",
    "query": "label_values(hadoop_jvm_metrics_gc_count, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "NameNode 状态",
   "type": "stat",
   "description": "0: 备用\n1: 活动",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hadoop_namenode_status", "legendFormat": "{{ host }}" }
   ]
  },
  {
   "title": "SystemLoadAverage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": " hadoop_os_system_load_average{host=~\"$Host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "graph",
   "description": "0: offline\n1: online",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_node_status{host=~\"$Host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_jvm_metrics_gc_count{host=~\"$Host\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HDFS 空间 （总）",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_namenode_fs_name_system_capacity_total{host=\"$Namenode\"}",
     "legendFormat": "总空间 "
    },
    {
     "expr": "hadoop_namenode_fs_name_system_capacity_used{host=\"$Namenode\"}",
     "legendFormat": "已使用"
    },
    {
     "expr": "hadoop_namenode_fs_name_system_capacity_used_non_dfs{host=\"$Namenode\"}",
     "legendFormat": "非 DFS 占用"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_jvm_metrics_gc_time_millis{host=~\"$Host\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "堆外内存",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_jvm_metrics_mem_non_heap_used_m{host=~\"$Host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "堆内内存",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "hadoop_jvm_metrics_mem_heap_used_m/hadoop_jvm_metrics_mem_heap_max_m{host=~\"$Host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HDFS DataNodes IO Blocks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_namenode_fs_name_system_block_capacity{host=\"$Namenode\"}",
     "legendFormat": "总容量块数"
    },
    {
     "expr": "hadoop_namenode_fs_name_system_blocks_total{host=\"$Namenode\"}",
     "legendFormat": "已使用块数"
    },
    {
     "expr": "hadoop_namenode_fs_name_system_corrupt_blocks{host=\"$Namenode\"}",
     "legendFormat": "损坏副本数据块数"
    },
    {
     "expr": "hadoop_namenode_fs_name_system_excess_blocks{host=\"$Namenode\"}",
     "legendFormat": "多余块数"
    },
    {
     "expr": "hadoop_namenode_fs_name_system_missing_blocks{host=\"$Namenode\"}",
     "legendFormat": "丢失块数"
    },
    {
     "expr": "hadoop_namenode_fs_name_system_pending_deletion_blocks{host=\"$Namenode\"}",
     "legendFormat": "待定删除数据块数"
    },
    {
     "expr": "hadoop_namenode_fs_name_system_pending_replication_blocks{host=\"$Namenode\"}",
     "legendFormat": "待定复制数据块数"
    },
    {
     "expr": "hadoop_namenode_fs_name_system_scheduled_replication_blocks{host=\"$Namenode\"}",
     "legendFormat": "已计划复制数据块数"
    },
    {
     "expr": "hadoop_namenode_fs_name_system_under_replicated_blocks{host=\"$Namenode\"}",
     "legendFormat": "副本不足的块数"
    },
    {
     "expr": "hadoop_namenode_fs_name_system_files_total{host=\"$Namenode\"}",
     "legendFormat": "文件和目录块数"
    }
   ]
  },
  {
   "title": "客户端 operations ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hadoop_datanode_activity_reads_from_local_client[1m]))",
     "legendFormat": "从本地客户端的读取数"
    },
    {
     "expr": "sum(rate(hadoop_datanode_activity_reads_from_remote_client[1m]))",
     "legendFormat": "从远程客户端的读取数"
    },
    {
     "expr": "sum(rate(hadoop_datanode_activity_writes_from_local_client[1m]))",
     "legendFormat": "从本地客户端的写入数"
    },
    {
     "expr": "sum(rate(hadoop_datanode_activity_writes_from_remote_client[1m]))",
     "legendFormat": "从远程客户端的写入数"
    }
   ]
  },
  {
   "title": "DataNodes 收发器",
   "type": "graph",
   "description": "该实体的所有子级 DataNode 实体中经计算的 收发器 度量总和",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_datanode_activity_data_node_active_xceivers_count{host=~\"$Host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HDFS DataNodes Fsync",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_datanode_activity_fsync_count{host=~\"$Host\"}[1m])",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "HDFS DataNodes IO Blocks (总)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hadoop_datanode_activity_blocks_read[1m]))",
     "legendFormat": "读取块"
    },
    {
     "expr": "sum(rate(hadoop_datanode_activity_blocks_written[1m]))",
     "legendFormat": "写入块"
    },
    {
     "expr": "sum(rate(hadoop_datanode_activity_blocks_removed[1m]))",
     "legendFormat": "删除块"
    },
    {
     "expr": "sum(rate(hadoop_datanode_activity_blocks_verified[1m]))",
     "legendFormat": "验证块"
    },
    {
     "expr": "sum(rate(hadoop_datanode_activity_block_verification_failures[1m]))",
     "legendFormat": "块验证失败"
    }
   ]
  },
  {
   "title": "HDFS DataNodes Remote Read IO Bytes (总)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hadoop_datanode_activity_remote_bytes_read[1m]))",
     "legendFormat": "远端读取"
    }
   ]
  },
  {
   "title": "HDFS DataNodes Remote Read IO Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_datanode_activity_remote_bytes_read{host=~\"$Host\"}[30s])",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "HDFS DataNodes Remote Write IO Bytes (总)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hadoop_datanode_activity_remote_bytes_written[1m]))",
     "legendFormat": "远端写入"
    }
   ]
  },
  {
   "title": "HDFS DataNodes Remote Write IO Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_datanode_activity_remote_bytes_written{host=~\"$Host\"}[1m])",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "HDFS DataNodes Read IO Bytes (总)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hadoop_datanode_activity_bytes_read[1m]))",
     "legendFormat": "读取"
    }
   ]
  },
  {
   "title": "HDFS DataNodes Read IO Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_datanode_activity_bytes_read{host=~\"$Host\"}[1m])",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "HDFS DataNodes Write IO Bytes (总)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hadoop_datanode_activity_bytes_written{host=~\"$Host\"}[1m]))",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "HDFS DataNodes Write IO Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_datanode_activity_bytes_written{host=~\"$Host\"}[1m])",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "集群 DataNodes 磁盘刷新 (总)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hadoop_datanode_activity_flush_nanos_num_ops[1m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "集群 DataNodes 磁盘刷新",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_datanode_activity_flush_nanos_num_ops{host=~\"$Host\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "集群 DataNodes 磁盘刷新时间 (平均)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(hadoop_datanode_activity_flush_nanos_avg_time)",
     "legendFormat": "平均"
    }
   ]
  },
  {
   "title": "集群 DataNodes 磁盘刷新时间",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 62 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "hadoop_datanode_activity_flush_nanos_avg_time{host=~\"$Host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "DataNodes 发送数据包传输时间",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "hadoop_datanode_activity_send_data_packet_transfer_nanos_avg_time{host=~\"$Host\"}",
     "legendFormat": " {{host}}"
    }
   ]
  },
  {
   "title": "DataNodes   确认数据包往返时间",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "hadoop_datanode_activity_packet_ack_round_trip_time_nanos_avg_time{host=~\"$Host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "DataNodes 发送网络阻止数据包时间",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "hadoop_datanode_activity_send_data_packet_blocked_on_network_nanos_avg_time{host=~\"$Host\"}",
     "legendFormat": " {{host}}"
    }
   ]
  },
  {
   "title": "DataNodes   发送数据包 ops/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "increase(hadoop_datanode_activity_send_data_packet_transfer_nanos_num_ops{host=~\"$Host\"}[30s])/30",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "DataNodes   确认数据包 ops/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "increase(hadoop_datanode_activity_packet_ack_round_trip_time_nanos_num_ops{host=~\"$Host\"}[30s])/30",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "DataNodes 发送网络阻止数据包 ops/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "increase(hadoop_datanode_activity_send_data_packet_blocked_on_network_nanos_num_ops{host=~\"$Host\"}[30s])/30",
     "legendFormat": " {{host}}"
    }
   ]
  }
 ]
}