{
 "title": "Hbase Metrics From JMX",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "tableName",
    "label": "TableName",
    "query": "label_values(hbase_regionserver_regions_read_request_count, table)"
   }
  ]
 },
 "panels": [
  {
   "title": "HMaster 状态",
   "type": "stat",
   "description": "0: 备用\n1: 活动",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hbase_master_server_is_active_master",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "graph",
   "description": "0: offline\n1: online",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hbase_node_status", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Balancer 状态",
   "type": "stat",
   "description": "0: 备用\n1: 活动",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hbase_master_balancer_is_active_balancer",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Open Connections ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_ipc_num_open_connections",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "hbase_master_ipc_num_open_connections",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ActiveHandler",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_ipc_num_active_handler",
     "legendFormat": "Total: {{host}}"
    },
    {
     "expr": "hbase_regionserver_ipc_num_active_read_handler",
     "legendFormat": "Read: {{host}}"
    },
    {
     "expr": "hbase_regionserver_ipc_num_active_scan_handler",
     "legendFormat": "Sacn: {{host}}"
    },
    {
     "expr": "hbase_regionserver_ipc_num_active_write_handler",
     "legendFormat": "Write: {{host}}"
    },
    {
     "expr": "hbase_master_ipc_num_active_handler",
     "legendFormat": "Total: {{host}}"
    },
    {
     "expr": "hbase_master_ipc_num_active_read_handler",
     "legendFormat": "Read: {{host}}"
    },
    {
     "expr": "hbase_master_ipc_num_active_scan_handler",
     "legendFormat": "Sacn: {{host}}"
    },
    {
     "expr": "hbase_master_ipc_num_active_write_handler",
     "legendFormat": "Write: {{host}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(hbase_jvm_metrics_gc_count[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "SystemLoadAverage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hbase_os_system_load_average", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(hbase_jvm_metrics_gc_time_millis[30s])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HBase 已用空间 (总)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(hbase_regionserver_tables_store_file_size)",
     "legendFormat": "已用空间"
    }
   ]
  },
  {
   "title": "regionCount",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_server_region_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Merge and Split Plan",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hbase_master_server_merge_plan_count",
     "legendFormat": "Merge Plan: {{host}}"
    },
    {
     "expr": "hbase_master_server_split_plan_count",
     "legendFormat": "Split Plan: {{host}}"
    }
   ]
  },
  {
   "title": "Table ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hbase_regionserver_regions_read_request_count{table=\"$tableName\"}[1m])) by (namespace, table)",
     "legendFormat": "ReadRequest: {{namespace}}-{{table}}"
    },
    {
     "expr": "sum(irate(hbase_regionserver_regions_filtered_read_request_count{table=\"$tableName\"}[1m])) by (namespace, table)",
     "legendFormat": "FilteredReadRequest: {{namespace}}-{{table}}"
    },
    {
     "expr": "sum(irate(hbase_regionserver_regions_write_request_count{table=\"$tableName\"}[1m])) by (namespace, table)",
     "legendFormat": "WriteRequest: {{namespace}}-{{table}}"
    },
    {
     "expr": "sum(irate(hbase_regionserver_regions_append_count{table=\"$tableName\"}[1m])) by (namespace, table)",
     "legendFormat": "Append: {{namespace}}-{{table}}"
    },
    {
     "expr": "sum(irate(hbase_regionserver_regions_put_count{table=\"$tableName\"}[1m])) by (namespace, table)",
     "legendFormat": "Put: {{namespace}}-{{table}}"
    },
    {
     "expr": "sum(irate(hbase_regionserver_regions_increment_count{table=\"$tableName\"}[1m])) by (namespace, table)",
     "legendFormat": "Increment: {{namespace}}-{{table}}"
    },
    {
     "expr": "sum(irate(hbase_regionserver_regions_get_count{table=\"$tableName\"}[1m])) by (namespace, table)",
     "legendFormat": "Get: {{namespace}}-{{table}}"
    },
    {
     "expr": " sum(irate(hbase_regionserver_regions_scan_count{table=\"$tableName\"}[1m])) by (namespace, table)",
     "legendFormat": "Scan: {{namespace}}-{{table}}"
    },
    {
     "expr": "sum(irate(hbase_regionserver_regions_delete_count{table=\"$tableName\"}[1m])) by (namespace, table)",
     "legendFormat": "Delete: {{namespace}}-{{table}}"
    }
   ]
  },
  {
   "title": "WAL Append Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(hbase_regionserver_wal_append_time_num_ops[1m])",
     "legendFormat": "Append: {{host}}"
    }
   ]
  },
  {
   "title": "WAL Append Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(hbase_regionserver_wal_written_bytes[1m])",
     "legendFormat": " {{host}}"
    }
   ]
  },
  {
   "title": "readRequestRate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(hbase_regionserver_tables_read_request_count{table=\"$tableName\"}[1m])",
     "legendFormat": "{{host}}  {{namespace}}-{{table}}:"
    }
   ]
  },
  {
   "title": "Disk Read OPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(hbase_regionserver_io_fs_pre_read_time_num_ops[1m])",
     "legendFormat": "PRead: {{host}}"
    },
    {
     "expr": "irate(hbase_regionserver_io_fs_read_time_num_ops[1m])",
     "legendFormat": "Read: {{host}}"
    }
   ]
  },
  {
   "title": "writeRequestRate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(hbase_regionserver_tables_write_request_count{table=\"$tableName\"}[1m])",
     "legendFormat": "{{host}} {{namespace}}-{{table}}: "
    }
   ]
  },
  {
   "title": "Disk Write OPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(hbase_regionserver_io_fs_write_time_num_ops[1m])",
     "legendFormat": "Write: {{host}}"
    }
   ]
  },
  {
   "title": "Region StoreFile Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_regions_store_file_size{table=\"$tableName\"}",
     "legendFormat": "{{ namespace }}- {{ table }} - {{ host }} - {{ region }}"
    }
   ]
  },
  {
   "title": "Region StoreFile Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_regions_store_file_count{table=\"$tableName\"}",
     "legendFormat": "{{ namespace }}- {{ table }} - {{ host }} - {{ region }}"
    }
   ]
  },
  {
   "title": "smallCompactionQueueLength",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_server_small_compaction_queue_length",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Compaction OPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(hbase_regionserver_server_compaction_time_num_ops[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Compacted Cells Count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hbase_regionserver_server_compacted_cells_count[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Compacted Cells Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(hbase_regionserver_server_compacted_cells_size[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "compactionQueueLength",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_server_compaction_queue_length",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Compaction OPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(hbase_regionserver_server_major_compaction_time_num_ops[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "majorCompactedCellsCount",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hbase_regionserver_server_major_compacted_cells_count[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "majorCompactedCellsSize",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(hbase_regionserver_server_major_compacted_cells_size[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "updatesBlockedTime",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_server_updates_blocked_time",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "WALRollRequest",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(hbase_regionserver_wal_roll_request[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "FlushQueueLength",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_server_flush_queue_length",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "memStoreSize",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_server_mem_store_size",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "storeFileCount",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_server_store_file_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "storeFileSize By Table",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(hbase_regionserver_regions_store_file_count) by (namespace, table)",
     "legendFormat": "{{namespace}}-{{table}}"
    }
   ]
  },
  {
   "title": "storeFileSize By Host",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(hbase_regionserver_regions_store_file_size) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "blockCacheRate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(hbase_regionserver_server_block_cache_hit_count[1m])",
     "legendFormat": "Hit: {{host}}"
    },
    {
     "expr": "irate(hbase_regionserver_server_block_cache_miss_count[1m])",
     "legendFormat": "Miss: {{host}}"
    },
    {
     "expr": "rate(hbase_regionserver_server_block_cache_bloom_chunk_miss_count[1m])",
     "legendFormat": "BloomChunkMiss: {{host}}"
    }
   ]
  },
  {
   "title": "blockCache 命中率",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_server_block_cache_express_hit_percent",
     "legendFormat": "ExpressHit: {{host}}"
    }
   ]
  },
  {
   "title": "blockCacheSize",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_server_block_cache_size",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "percentFilesLocal",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "hbase_regionserver_server_percent_files_local",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}